name: Scala CI
on:
  pull_request:
  push:
    branches: [ master, main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12.18, 2.13.13]
        spark: [3.4.3, 3.5.1]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
      - name: Cache Ivy/Coursier
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-ivy-${{ hashFiles('**/*.sbt','project/**') }}
      - name: Create local.sbt overrides
        run: |
          echo 'ThisBuild / scalaVersion := "${{ matrix.scala }}"' > local.sbt
          echo 'ThisBuild / crossScalaVersions := Seq("2.12.18","2.13.13")' >> local.sbt
          echo 'val sparkVer = "${{ matrix.spark }}"' >> local.sbt
      - name: Test
        run: sbt -v clean test
